svn merge  --non-interactive https://source.sakaiproject.org/svn/access/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/access/tags/sakai-2.9.0-rc01 access
svn merge  --non-interactive https://source.sakaiproject.org/svn/alias/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/alias/tags/sakai-2.9.0-rc01 alias
svn merge  --non-interactive https://source.sakaiproject.org/svn/archive/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/archive/tags/sakai-2.9.0-rc01 archive
svn merge  --non-interactive https://source.sakaiproject.org/svn/authz/tags/sakai-2.8.0-rc04  https://source.sakaiproject.org/svn/authz/tags/sakai-2.9.0-rc01  authz
svn merge  --non-interactive https://source.sakaiproject.org/svn/chat/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/chat/tags/sakai-2.9.0-rc01 chat
svn merge  --non-interactive https://source.sakaiproject.org/svn/citations/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/citations/tags/sakai-2.9.0-rc01 citations
svn merge  --non-interactive https://source.sakaiproject.org/svn/config/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/config/tags/sakai-2.9.0-rc01 config
svn merge  --non-interactive https://source.sakaiproject.org/svn/content/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/content/tags/sakai-2.9.0-rc01  content
svn merge  --non-interactive https://source.sakaiproject.org/svn/dav/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/dav/tags/sakai-2.9.0-rc01 dav
svn merge  --non-interactive https://source.sakaiproject.org/svn/gradebook/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/gradebook/tags/sakai-2.9.0-rc01 gradebook
svn merge  --non-interactive https://source.sakaiproject.org/svn/help/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/help/tags/sakai-2.9.0-rc01  help
svn merge  --non-interactive https://source.sakaiproject.org/svn/linktool/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/linktool/tags/sakai-2.9.0-rc01  linktool
svn merge  --non-interactive https://source.sakaiproject.org/svn/login/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/login/tags/sakai-2.9.0-rc01 login
svn merge  --non-interactive https://source.sakaiproject.org/svn/master/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/master/tags/sakai-2.9.0-rc01 master
svn merge  --non-interactive https://source.sakaiproject.org/svn/memory/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/memory/tags/sakai-2.9.0-rc01 memory
svn merge  --non-interactive https://source.sakaiproject.org/svn/metaobj/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/metaobj/tags/sakai-2.9.0-rc01  metaobj
svn merge  --non-interactive https://source.sakaiproject.org/svn/osp/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/osp/tags/sakai-2.9.0-rc01  osp
svn merge  --non-interactive https://source.sakaiproject.org/svn/pack/tags/pack-2.8.0-rc04 https://source.sakaiproject.org/svn/pack/tags/sakai-2.9.0-rc01  pack
svn merge  --non-interactive https://source.sakaiproject.org/svn/podcasts/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/podcasts/tags/sakai-2.9.0-rc01  podcasts
svn merge  --non-interactive https://source.sakaiproject.org/svn/postem/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/postem/tags/sakai-2.9.0-rc01  postem
svn merge  --non-interactive https://source.sakaiproject.org/svn/providers/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/providers/tags/sakai-2.9.0-rc01  providers
svn merge  --non-interactive https://source.sakaiproject.org/svn/reference/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/reference/tags/sakai-2.9.0-rc01   reference
svn merge  --non-interactive https://source.sakaiproject.org/svn/rights/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/rights/tags/sakai-2.9.0-rc01   rights
svn merge  --non-interactive https://source.sakaiproject.org/svn/roster/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/roster/tags/sakai-2.9.0-rc01  roster
svn merge  --non-interactive https://source.sakaiproject.org/svn/rwiki/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/rwiki/tags/sakai-2.9.0-rc01    rwiki
svn merge  --non-interactive https://source.sakaiproject.org/svn/sections/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/sections/tags/sakai-2.9.0-rc01   sections
svn merge  --non-interactive https://source.sakaiproject.org/svn/site-manage/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/site-manage/tags/sakai-2.9.0-rc01   site-manage
svn merge  --non-interactive https://source.sakaiproject.org/svn/syllabus/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/syllabus/tags/sakai-2.9.0-rc01  syllabus
svn merge  --non-interactive https://source.sakaiproject.org/svn/textarea/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/textarea/tags/sakai-2.9.0-rc01   textarea
svn merge  --non-interactive https://source.sakaiproject.org/svn/tool/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/tool/tags/sakai-2.9.0-rc01   tool
svn merge  --non-interactive https://source.sakaiproject.org/svn/user/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/user/tags/sakai-2.9.0-rc01     user
svn merge  --non-interactive https://source.sakaiproject.org/svn/usermembership/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/usermembership/tags/sakai-2.9.0-rc01  usermembership
svn merge  --non-interactive https://source.sakaiproject.org/svn/warehouse/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/warehouse/tags/sakai-2.9.0-rc01   warehouse
svn merge  --non-interactive https://source.sakaiproject.org/svn/web/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/web/tags/sakai-2.9.0-rc01  web
svn merge  --non-interactive https://source.sakaiproject.org/svn/kernel/tags/kernel-1.3.0-rc01 https://source.sakaiproject.org/svn/kernel/tags/kernel-1.3.0-rc01   kernel
svn merge  --non-interactive https://source.sakaiproject.org/svn/common/tags/common-1.1.1 https://source.sakaiproject.org/svn/common/tags/common-1.2.0-rc01 common
svn merge  --non-interactive https://source.sakaiproject.org/svn/content-review/tags/contentreview-2.8.4    https://source.sakaiproject.org/svn/content-review/tags/contentreview-2.9.2-rc01    contentreview
svn merge  --non-interactive https://source.sakaiproject.org/svn/edu-services/tags/edu-services-1.1.1 https://source.sakaiproject.org/svn/edu-services/tags/edu-services-1.2.0-rc01         edu-services
svn merge  --non-interactive https://source.sakaiproject.org/svn/emailtemplateservice/tags/emailtemplateservice-0.5.1   https://source.sakaiproject.org/svn/emailtemplateservice/tags/emailtemplateservice-0.6.0-rc01  emailtemplateservice
svn merge  --non-interactive https://source.sakaiproject.org/svn/entitybroker/tags/entitybroker-1.4.1    https://source.sakaiproject.org/svn/entitybroker/tags/entitybroker-1.5.0-rc01   entitybroker
svn merge  --non-interactive https://source.sakaiproject.org/svn/jsf/tags/jsf-2.8.1     https://source.sakaiproject.org/svn/jsf/tags/jsf-2.9.0-rc01    jsf
svn merge  --non-interactive https://source.sakaiproject.org/svn/sakai-mock/tags/sakai-mock-2.8.1   https://source.sakaiproject.org/svn/sakai-mock/tags/sakai-mock-2.9.0-rc01  sakai-mock
svn merge  --non-interactive https://source.sakaiproject.org/svn/webservices/tags/webservices-1.0.1   https://source.sakaiproject.org/svn/webservices/tags/webservices-1.1.0-rc01  webservices
svn merge  --non-interactive https://source.sakaiproject.org/svn/basiclti/tags/basiclti-1.3.1 https://source.sakaiproject.org/svn/basiclti/tags/basiclti-2.0.0-rc01    basiclti
svn merge  --non-interactive https://source.sakaiproject.org/svn/scheduler/tags/jobscheduler-2.8.0-rc04   https://source.sakaiproject.org/svn/jobscheduler/tags/scheduler-2.9.0-rc01    scheduler
svn merge  --non-interactive https://source.sakaiproject.org/svn/mailsender/tags/1.6.3 https://source.sakaiproject.org/svn/mailsender/tags/1.7.0-rc01         mailsender
svn merge  --non-interactive https://source.sakaiproject.org/svn/msgcntr/tags/msgcntr-2.8.0-rc04    https://source.sakaiproject.org/svn/msgcntr/tags/msgcntr-3.0.0-rc01   msgcntr
svn merge  --non-interactive https://source.sakaiproject.org/svn/polls/tags/polls-1.4.1    https://source.sakaiproject.org/svn/polls/tags/polls-1.5.0-rc01                       polls
svn merge  --non-interactive https://source.sakaiproject.org/svn/profile/tags/profile-2.8.1    https://source.sakaiproject.org/svn/profile/tags/profile-2.9.0-rc01        profile
svn merge  --non-interactive https://source.sakaiproject.org/svn/profile2/tags/profile2-1.4.0-rc04  https://source.sakaiproject.org/svn/profile2/tags/profile2-1.5.0-rc01        profile2
svn merge  --non-interactive https://source.sakaiproject.org/svn/reset-pass/tags/reset-pass-2.8.1   https://source.sakaiproject.org/svn/reset-pass/tags/reset-pass-2.9.0-rc01    reset-pass
svn merge  --non-interactive https://source.sakaiproject.org/svn/sam/tags/samigo-2.8.0-rc05     https://source.sakaiproject.org/svn/sam/tags/samigo-2.9.0-rc01       sam
svn merge  --non-interactive https://source.sakaiproject.org/svn/search/tags/search-1.3.2  https://source.sakaiproject.org/svn/search/tags/search-1.4.0-rc01         search
svn merge  --non-interactive https://source.sakaiproject.org/svn/shortenedurl/tags/shortenedurl-1.0.1   https://source.sakaiproject.org/svn/shortenedurl/tags/shortenedurl-1.1.0-rc01   shortenedurl
svn merge  --non-interactive https://source.sakaiproject.org/svn/sitestats/tags/sitestats-2.2.0-rc04   https://source.sakaiproject.org/svn/sitestats/tags/sitestats-2.3.0-rc01    sitestats
svn merge  --non-interactive https://source.sakaiproject.org/svn/announcement/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/announcement/tags/announcement-2.9.0-rc01 announcement
svn merge  --non-interactive https://source.sakaiproject.org/svn/assignment/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/assignment/tags/assignment-2.9.0-rc01 assignment
svn merge  --non-interactive https://source.sakaiproject.org/svn/calendar/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/calendar/tags/calendar-2.9.0-rc01  calendar
svn merge  --non-interactive https://source.sakaiproject.org/svn/courier/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/courier/tags/courier-2.9.0-rc01 courier
svn merge  --non-interactive https://source.sakaiproject.org/svn/mailarchive/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/mailarchive/tags/mailarchive-2.9.0-rc01 mailarchive
svn merge  --non-interactive https://source.sakaiproject.org/svn/message/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/message/tags/message-2.9.0-rc01  message
svn merge  --non-interactive https://source.sakaiproject.org/svn/portal/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/portal/tags/portal-2.9.0-rc01   portal
svn merge  --non-interactive https://source.sakaiproject.org/svn/presence/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/presence/tags/presence-2.9.0-rc01  presence
svn merge  --non-interactive https://source.sakaiproject.org/svn/site/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/site/tags/site-2.9.0-rc01    site
svn merge  --non-interactive https://source.sakaiproject.org/svn/taggable/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/taggable/tags/taggable-2.9.0-rc01   taggable
svn merge  --non-interactive https://source.sakaiproject.org/svn/velocity/tags/sakai-2.8.0-rc04 https://source.sakaiproject.org/svn/velocity/tags/velocity-2.9.0-rc01   velocity
svn merge  --non-interactive https://source.sakaiproject.org/svn/hybrid/tags/hybrid-1.1.3  https://source.sakaiproject.org/svn/hybrid/tags/hybrid-1.2.0-rc01  hyrid
